FROM node:latest as build-stage
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:latest as runtime-stage
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build ./build
COPY --from=build-stage /usr/src/app/package*.json ./
RUN npm install --production
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "npm", "start" ]
