FROM node:latest AS build-stage
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:latest AS runtime-stage
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build ./build
EXPOSE 3000
ENV NODE_ENV=production
RUN npm install --production serve
CMD [ "npx", "serve", "-s", "build" ]
