version: '3.8'
services:
  cbot-server:
    image: cbot-server:v1.0
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
       PORT: 4000
    env_file:
      - ./server/.env
    volumes:
      - ./server/index.js:/usr/src/app/index.js
  cbot-client:
    image: cbot-client:v1.0
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
       REACT_APP_GPT_SERVER_ENDPOINT: "http://localhost:4000"
    env_file:
      - ./client/.env
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    command: [ "npm", "start" ]
    depends_on:
      - cbot-server