version: '3.8'
services:
  cbot-server:
    image: cbot-server:v1.0
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  cbot-client:
    image: cbot-client:v1.0
    build: 
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    depends_on:
      - cbot-server