version: '3.8'
services:
  cbot-server:
    image: cbot-server:v1.0
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server/index.js:/usr/src/app/index.js
  cbot-client:
    image: cbot-client:v1.0
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    depends_on:
      - cbot-server